services:
  turtlebot-core:
    image: nobel86/turtlebot-rpi5:latest
    network_mode: host
    stdin_open: true
    tty: true  
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///root/turtlebot3_ws/cylconedds_config.xml
      - LDS_MODEL=${LDS_MODEL}
      - TURTLEBOT3_MODEL=burger
      - TURTLEBOT3_NAME=TB3_${TURTLEBOT_NR}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}

    container_name: turtlebot_${TURTLEBOT_NR}
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: bash 
    devices:
      - /dev/ttyACM0:/dev/ttyACM0  # OpenCR
      - /dev/ttyUSB0:/dev/ttyUSB0  # LDS 01 - laser lidar
      - /dev/input/js0:/dev/input/js0  # Logitech F710 Gamepad
      - /dev/video0:/dev/video0  # Camera
